version: "3"
services:
  db_service:
    restart: always
    image: postgres:13
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data


  booking_service:
    restart: always
    image: booking_image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    env_file: .env
    command: python3 main.py
    depends_on:
      - db_service
    links:
      - db_service:postgres
