version: "3"
services:
  db_service:
    restart: always
    image: postgres:13
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data


  booking_service:
    restart: always
    image: booking_image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=my_password
      - DB_HOST=db_service
      - DB_PORT=5432
    command: bash -c "python3 -m alembic upgrade head && python3 main.py"
    depends_on:
      - db_service
    links:
      - db_service:postgres